org: prawee
# app: greet
service: greet
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-7

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
