org: prawee
app: greet
service: greet
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
